FROM docker.n8n.io/n8nio/n8n:latest

USER root
WORKDIR /home/node
USER node

# 创建数据目录
RUN mkdir -p /home/node/.n8n

# 设置环境变量（这些会被Render的环境变量覆盖）
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=${N8N_DATABASE_POSTGRESDB_DATABASE}
ENV DB_POSTGRESDB_HOST=${N8N_DATABASE_POSTGRESDB_HOST}
ENV DB_POSTGRESDB_PORT=${N8N_DATABASE_POSTGRESDB_PORT}
ENV DB_POSTGRESDB_USER=${N8N_DATABASE_POSTGRESDB_USER}
ENV DB_POSTGRESDB_PASSWORD=${N8N_DATABASE_POSTGRESDB_PASSWORD}
ENV DB_POSTGRESDB_SSL_ENABLED=${N8N_DATABASE_POSTGRESDB_SSL}

EXPOSE 5678

# 使用VOLUME声明数据目录
VOLUME ["/home/node/.n8n"]

# 启动n8n
CMD ["n8n"]
